package arnie.data;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import arnie.data.MuscleGroupDao;
import arnie.data.ExerciseDao;
import arnie.data.ExerciseMuscleGroupRefDao;
import arnie.data.WorkoutSessionDao;
import arnie.data.ExerciseSetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 6): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 6;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        MuscleGroupDao.createTable(db, ifNotExists);
        ExerciseDao.createTable(db, ifNotExists);
        ExerciseMuscleGroupRefDao.createTable(db, ifNotExists);
        WorkoutSessionDao.createTable(db, ifNotExists);
        ExerciseSetDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        MuscleGroupDao.dropTable(db, ifExists);
        ExerciseDao.dropTable(db, ifExists);
        ExerciseMuscleGroupRefDao.dropTable(db, ifExists);
        WorkoutSessionDao.dropTable(db, ifExists);
        ExerciseSetDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(MuscleGroupDao.class);
        registerDaoClass(ExerciseDao.class);
        registerDaoClass(ExerciseMuscleGroupRefDao.class);
        registerDaoClass(WorkoutSessionDao.class);
        registerDaoClass(ExerciseSetDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
