/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fortius.arnie.data.interop;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SyncResponseType implements org.apache.thrift.TEnum {
  ALL_SYNC(0),
  MISSING_SESSIONS(1),
  EXERCISES_SYNC(2),
  MISSING_EXERCISES(3);

  private final int value;

  private SyncResponseType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SyncResponseType findByValue(int value) { 
    switch (value) {
      case 0:
        return ALL_SYNC;
      case 1:
        return MISSING_SESSIONS;
      case 2:
        return EXERCISES_SYNC;
      case 3:
        return MISSING_EXERCISES;
      default:
        return null;
    }
  }
}
