/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fortius.arnie.data.interop;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SyncRequestType implements org.apache.thrift.TEnum {
  SYNC_TIME_RANGES(0),
  SYNC_SESSIONS(1),
  SYNC_EXERCISES(2);

  private final int value;

  private SyncRequestType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SyncRequestType findByValue(int value) { 
    switch (value) {
      case 0:
        return SYNC_TIME_RANGES;
      case 1:
        return SYNC_SESSIONS;
      case 2:
        return SYNC_EXERCISES;
      default:
        return null;
    }
  }
}
