package com.fortius.arnie.data;

import java.util.List;
import com.fortius.arnie.data.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSCLE_GROUP.
 */
public class MuscleGroup {

    private Long id;
    private String name;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MuscleGroupDao myDao;

    private List<ExerciseMuscleGroupRef> exerciseRefs;

    public MuscleGroup() {
    }

    public MuscleGroup(Long id) {
        this.id = id;
    }

    public MuscleGroup(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMuscleGroupDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ExerciseMuscleGroupRef> getExerciseRefs() {
        if (exerciseRefs == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ExerciseMuscleGroupRefDao targetDao = daoSession.getExerciseMuscleGroupRefDao();
            List<ExerciseMuscleGroupRef> exerciseRefsNew = targetDao._queryMuscleGroup_ExerciseRefs(id);
            synchronized (this) {
                if(exerciseRefs == null) {
                    exerciseRefs = exerciseRefsNew;
                }
            }
        }
        return exerciseRefs;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetExerciseRefs() {
        exerciseRefs = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
